### ISSUE TITLE
[Feature] 전투 이펙트

### ISSUE THREAD

**Issue by Danny-Caesar** [pknu-wap/2024-1-Game-2-Team#66]
## ⚙️ 기능 설명

전투 씬에서 사용되는 이펙트를 개발합니다

## 📚 할 일 목록

- [x] 카드 별 이펙트 오브젝트 구현하기
- [x] 카드를 사용할 때 이펙트 실행하기
- [x] 적 오브젝트에 데미지 입는  모션 추가

### 파티클
https://devparklibrary.tistory.com/13
https://www.youtube.com/watch?v=2De-Bp262eE&t=1s
https://www.youtube.com/watch?time_continue=47&v=YtrOYF8r7lc&embeds_referring_euri=https%3A%2F%2Fgamefx.co.kr%2F&source_ve_path=MjM4NTE&feature=emb_title

**Comment by miniron-v** [comment]
Type보단 카드별... 이 맞는 것 같기도? (전기톱과 돌맹이)

**Comment by Danny-Caesar** [comment]
각 카드 별로 만들어보겠습니다 그럼
