### ISSUE TITLE
[Bug] 카드 타게팅 오류

### ISSUE THREAD

**Issue by Danny-Caesar** [pknu-wap/2024-1-Game-2-Team#71]
## ❓ 어떤 버그인가요?

타게팅 카드를 선택한 채로 선택 중인 카드를 더블 클릭하면 카드 포커싱과 화살표가 죽는 버그 발생
## 📱 스크린샷 & 참고 자료

<img width="694" alt="image" src="https://github.com/pknu-wap/2024-1-Game-2-Team/assets/125544913/5c077f61-7c2f-47c4-8f81-ef289f10f3c4">

**Comment by miniron-v** [comment]
#84 에서 고쳤습니다.
