### ISSUE TITLE
[Bug] 패 털기 중 카드 사용 버그

### ISSUE THREAD

**Issue by Danny-Caesar** [pknu-wap/2024-1-Game-2-Team#72]
## ❓ 어떤 버그인가요?

카드를 드로우하거나 버릴 때 날아가는 카드를 잡아 사용할 수 있는 버그
## 💣 원인

CardManager.cs에 isDrawing, isDiscarding 변수 같은 걸 만들어서 Card.cs에서 싱글톤으로 확인해야 할 듯

**Comment by miniron-v** [comment]
#84 에서 고쳤습니다.
